### ISSUE TITLE
Structure of the generated object

### ISSUE THREAD

**Issue by gubagu** [danheberden/jquery-serializeForm#11]
Hi Dan,
First of all Great plugin Thanks for sharing !

I am banging my head against the wall for the last 1 hour and I could't figure it out...

Is it possible by using only the input fields to create an object array something like:
        {block: [
           {
               room: "office",
               people: [
                   { first_name: "Jane", last_name: "Doe"},
                   { first_name: "John", last_name: "Doe" }
               ]
           },
           {
               room: "cantine",
               people: [
                   { first_name: "Juba", last_name: "Laba"},
                   { first_name: "Bono", last_name: "Boo" }
               ]
           }
        ]}

Thanks in advance,
Cheers,
Guby

**Comment by danheberden** [comment]
Hmm, that would require query params to support `block[][people][first_name]` - it might be a worthwhile thing to support that here. Currently, you'd have to name the index: http://jsbin.com/oduvor/2/edit

**Comment by gubagu** [comment]
Thanks for your answer and time putting together the demo !
I got to the same conclusion.
I'll be watching the repo for "[]" feature :)

Cheers,
Guby

**Comment by danheberden** [comment]
So in working on this, it presents a problem of object iteration. That is, this is assuming the objects will be looped through (and would be in the DOM) in order. Also, knowing when to hop in and out of objects, when there's no real indication of such is, well, a mind fuck. I think this could be merged/achieved with https://github.com/danheberden/jquery-serializeForm/issues/12 - which would fix both issues. The result would be providing which index the object belongs in: `block[0][people][first_name]`, `block[1][people][first_name]` and would be easy to track in a dynamicly generated setting.

**Comment by danheberden** [comment]
Fixed #12 and added a test for this use case https://github.com/danheberden/jquery-serializeForm/commit/b3b62b7039fcd1bc1f6e7c89feef1ae9ce49532d
