### ISSUE TITLE
Disabled inputs are also added in the result

### ISSUE THREAD

**Issue by rlemaire** [danheberden/jquery-serializeForm#14]
Hi,

The disabled inputs are also added in the result.

For instance this input : 

<input type="text" name="test" value="" disabled="disabled" />

Will generate : 

{
    "test" : ""
}

This is unexpected since in a simple post this inputs would be excluded.

Regards,

**Comment by danheberden** [comment]
Fixed in https://github.com/danheberden/jquery-serializeForm/commit/ce6d07ea01935e95dd2d70086721ebebfd46ae11
