### ISSUE TITLE
serializeObject does not serialize when targeting :input objects

### ISSUE THREAD

**Issue by raphael-lacerda** [danheberden/jquery-serializeForm#7]
jQuery's official .serialize() and .serializeArray() functions return the serialization result even if you provide an :input object or a collection of those, which is very useful sometimes. Currently, .serializeObject() only works if you provide a form object or any object that contains :input objects. In order to make .serializeObject() work like the official jQuery functions mentioned before, you folks just need to modify a small part of the code. I propose the following:

/*
- serializeObject
- https://github.com/danheberden/serializeObject
  *
- Copyright (c) 2012 Dan Heberden
- Licensed under the MIT, GPL licenses.
  */
  (function( $ ){
  $.fn.serializeObject = function() {
    if ( this.length < 1) {
      return false;
    }
  
    var $el = this;
    var data = {};
    var lookup = data; //current reference of data
  
    if($el.is(':input')){
        $inputElements = $el.filter( ':input[type!="checkbox"][type!="radio"], input:checked' );
    }else{
        $inputElements = $el.find( ':input[type!="checkbox"][type!="radio"], input:checked' );
    }
  
    $inputElements.each( function() {
      // data[a][b] becomes [ data, a, b ]
      var named = this.name.replace(/[([^]]+)?]/g, ',$1').split(',');
      var cap = named.length - 1;
  
  ```
  // Ensure that only elements with valid `name` properties will be serialized
  if ( named[ 0 ] ) {
    for ( var i = 0; i < cap; i++ ) {
        // move down the tree - create objects or array if necessary
        lookup = lookup[ named[i] ] = lookup[ named[i] ] ||
            ( named[ i + 1 ] === "" ? [] : {} );
    }
  
    // at the end, push or assign the value
    if ( lookup.length !== undefined ) {
         lookup.push( $( this ).val() );
    }else {
          lookup[ named[ cap ] ] = $( this ).val();
    }
  
    // assign the reference back to root
    lookup = data;
  }
  ```
  
    });
  
    return data;
  };
  }( jQuery ));

**Comment by danheberden** [comment]
Also see https://github.com/danheberden/serializeObject/commit/43e17c414263901a4bd67ca68ba2acb016bce895
